-- MySQL Script generated by MySQL Workbench
-- Sat Jul 23 22:44:30 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`category` ;

CREATE TABLE IF NOT EXISTS `mydb`.`category` (
  `category_id` INT NOT NULL,
  `parent_category_id` INT NULL,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`category_id`),
  UNIQUE INDEX `category_id_UNIQUE` (`category_id` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `mydb`.`image`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`image` ;

CREATE TABLE IF NOT EXISTS `mydb`.`image` (
  `idimage` INT NOT NULL,
  `image` CHAR(45) NULL,
  `alt` VARCHAR(45) NULL COMMENT 'База хранит изображения товаров, ',
  PRIMARY KEY (`idimage`),
  UNIQUE INDEX `idimage_UNIQUE` (`idimage` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`product` ;

CREATE TABLE IF NOT EXISTS `mydb`.`product` (
  `idproduct` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  `price` INT NULL,
  `discount_price` INT NULL,
  `promo_price` INT NULL,
  `description` VARCHAR(45) NULL,
  `main_image` INT NOT NULL,
  PRIMARY KEY (`idproduct`, `main_image`),
  UNIQUE INDEX `idproduct_UNIQUE` (`idproduct` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`image_has_product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`image_has_product` ;

CREATE TABLE IF NOT EXISTS `mydb`.`image_has_product` (
  `image_idimage` INT NOT NULL,
  `product_idproduct` INT NOT NULL,
  PRIMARY KEY (`image_idimage`, `product_idproduct`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`category_has_product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`category_has_product` ;

CREATE TABLE IF NOT EXISTS `mydb`.`category_has_product` (
  `category_category_id` INT NOT NULL,
  `product_idproduct` INT NOT NULL,
  PRIMARY KEY (`category_category_id`, `product_idproduct`));


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
